build:
  environment:
    php: '7.3'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:

build_failure_conditions:
  - 'project.metric("scrutinizer.quality", < 9.88)'
