language: php
dist: trusty

git:
    depth: 3

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-rm xdebug.ini
    - nvm install 10

install:
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - npm ci
    - npm install -g git+https://github.com/spryker-sdk/frontend-sniffer.git#semver:^0.2.2

script:
    - composer cs-check
    - frontend-sniffer --config ./ --path ../../ --level-restriction core
    - npm run formatter
    - npm run stylelint
    - npm run tslint

notifications:
    email: false
