name: CI

on: [push]

jobs:
    prefer-lowest:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.3']

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - name: Composer prefer lowest
              run: composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction

            - name: Install prefer lowest tool
              run: composer require --dev dereuromark/composer-prefer-lowest

            - name: Prefer lowest run
              run: vendor/bin/validate-prefer-lowest || true
