language: php

php:
    - 7.3
    - 7.4

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

script:
    - composer phpstan
    - composer cs-check

notifications:
    email: false
